//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
 
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace WindowsFormsApplication1
{
    //#region Contexts

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
  

    //#endregion
}